// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ADq6umPeDAPyywMv4l7QjAxGVOESC5U',
    appId: '1:747885108061:web:85ede6b46bc9a6166ae6b4',
    messagingSenderId: '747885108061',
    projectId: 'sumaq-a2de4',
    authDomain: 'sumaq-a2de4.firebaseapp.com',
    storageBucket: 'sumaq-a2de4.firebasestorage.app',
    measurementId: 'G-Y3YRM5ZYEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6X1v9eWxRq3Edyp20nYBuvEpaKt8H6A',
    appId: '1:747885108061:android:72c66c7ed3b3fa576ae6b4',
    messagingSenderId: '747885108061',
    projectId: 'sumaq-a2de4',
    storageBucket: 'sumaq-a2de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DMyLAYL1sZXqDHfs9EDTJ1xXpwRQkhs',
    appId: '1:747885108061:ios:6ce88ada65fa61f96ae6b4',
    messagingSenderId: '747885108061',
    projectId: 'sumaq-a2de4',
    storageBucket: 'sumaq-a2de4.firebasestorage.app',
    iosBundleId: 'com.example.moviles',
  );

}